[build]
  publish = "client"

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"     # 👈 MUST have this line

[functions."*"]
  timeout = 26                 # (your Pro-plan limit)
